version: '3.9'

services:

  app:
    build:
      context: src/app
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: "host"

  cpp-builder:
    image: cpp-builder:latest
    build:
      context: src/cpp-builder
    
    profiles:
      - neverstart
